#!/usr/bin/env python3
"""Render the combined Markdown manuscript to a print-ready PDF with ReportLab.

Usage (from the repository root, with the build virtualenv active):

    python3 java-backend-interview-book/scripts/build_book.py     # refresh the combined Markdown
    python3 java-backend-interview-book/scripts/build_pdf.py      # render the PDF

Requires: reportlab (rendering) and, for the verification step, pypdf.
Bootstrap:

    python3 -m venv .venv
    .venv/bin/pip install reportlab pypdf
    .venv/bin/python java-backend-interview-book/scripts/build_pdf.py

Pandoc, LaTeX, wkhtmltopdf and WeasyPrint are not used: none of them are
available in the build environment this book was produced in, so the PDF is
generated by a self-contained ReportLab pipeline that supports the features the
book needs - title page, clickable table of contents, PDF outline bookmarks,
page numbers, tables and monospaced code blocks.

The Markdown subset understood here is exactly what the manuscript uses:
ATX headings, paragraphs, bullet lists, fenced code blocks, pipe tables,
horizontal rules, bold, italic, inline code and links.
"""
from __future__ import annotations

import html
import re
import sys
from datetime import date
from pathlib import Path

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.platypus import (BaseDocTemplate, Frame, KeepTogether, ListFlowable,
                                    ListItem, PageBreak, PageTemplate, Paragraph,
                                    Preformatted, Spacer, Table, TableStyle)
    from reportlab.platypus.tableofcontents import TableOfContents
except ImportError:  # pragma: no cover - environment guidance
    sys.exit("reportlab is required: python3 -m venv .venv && "
             ".venv/bin/pip install reportlab pypdf")

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Java_Backend_Top_200_Interview_Questions.md"
OUTPUT = ROOT / "Java_Backend_Top_200_Interview_Questions.pdf"

TITLE = "Top 200 Java Backend Developer Interview Questions and Answers"
SUBTITLE = "For developers with 3-4 years of experience"

PAGE_W, PAGE_H = A4
MARGIN_X = 18 * mm
MARGIN_TOP = 18 * mm
MARGIN_BOTTOM = 20 * mm
FRAME_W = PAGE_W - 2 * MARGIN_X

ACCENT = colors.HexColor("#1F4E79")
ACCENT_LIGHT = colors.HexColor("#2E75B6")
CODE_BG = colors.HexColor("#F4F6F8")
CODE_BORDER = colors.HexColor("#D7DDE3")
RULE = colors.HexColor("#C9D2DA")

CODE_FONT = "Courier"
CODE_SIZE = 7.6
CODE_LEADING = 9.4


# --------------------------------------------------------------------------- styles
def build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    s: dict[str, ParagraphStyle] = {}
    s["body"] = ParagraphStyle(
        "body", parent=base["BodyText"], fontName="Helvetica", fontSize=9.4,
        leading=13.2, alignment=TA_JUSTIFY, spaceBefore=0, spaceAfter=6,
        textColor=colors.HexColor("#1A1A1A"))
    s["bullet"] = ParagraphStyle(
        "bullet", parent=s["body"], alignment=TA_JUSTIFY, spaceAfter=2.5, leading=12.6)
    s["chapter"] = ParagraphStyle(
        "chapter", parent=base["Heading1"], fontName="Helvetica-Bold", fontSize=19,
        leading=23, textColor=ACCENT, spaceBefore=0, spaceAfter=10, keepWithNext=True)
    s["section"] = ParagraphStyle(
        "section", parent=s["chapter"], fontSize=16, leading=20, spaceAfter=8)
    s["question"] = ParagraphStyle(
        "question", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=11.6,
        leading=14.6, textColor=ACCENT_LIGHT, spaceBefore=13, spaceAfter=5,
        keepWithNext=True)
    s["sub"] = ParagraphStyle(
        "sub", parent=base["Heading3"], fontName="Helvetica-Bold", fontSize=10.4,
        leading=13.4, textColor=colors.HexColor("#2F4858"), spaceBefore=9,
        spaceAfter=4, keepWithNext=True)
    s["code"] = ParagraphStyle(
        "code", parent=base["Code"], fontName=CODE_FONT, fontSize=CODE_SIZE,
        leading=CODE_LEADING, textColor=colors.HexColor("#14202B"),
        spaceBefore=0, spaceAfter=0, leftIndent=0, rightIndent=0)
    s["cell"] = ParagraphStyle(
        "cell", parent=s["body"], fontSize=8.1, leading=10.6, alignment=0, spaceAfter=0)
    s["cellhead"] = ParagraphStyle(
        "cellhead", parent=s["cell"], fontName="Helvetica-Bold", textColor=colors.white)
    s["title"] = ParagraphStyle(
        "title", parent=base["Title"], fontName="Helvetica-Bold", fontSize=27,
        leading=33, textColor=ACCENT, alignment=TA_CENTER, spaceAfter=10)
    s["subtitle"] = ParagraphStyle(
        "subtitle", parent=s["title"], fontSize=13.5, leading=18,
        textColor=colors.HexColor("#40566B"), spaceAfter=26)
    s["titlemeta"] = ParagraphStyle(
        "titlemeta", parent=s["body"], alignment=TA_CENTER, fontSize=10,
        leading=15, textColor=colors.HexColor("#33475B"))
    s["toctitle"] = ParagraphStyle(
        "toctitle", parent=s["chapter"], fontSize=17, spaceAfter=12)
    return s


def toc_styles() -> list[ParagraphStyle]:
    return [
        ParagraphStyle("toc0", fontName="Helvetica-Bold", fontSize=10, leading=15,
                       textColor=ACCENT, spaceBefore=6, firstLineIndent=0, leftIndent=0),
        ParagraphStyle("toc1", fontName="Helvetica", fontSize=8.4, leading=11.2,
                       textColor=colors.HexColor("#2A2A2A"), leftIndent=14,
                       firstLineIndent=0),
    ]


# --------------------------------------------------------------------------- inline
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD_RE = re.compile(r"\*\*(.+?)\*\*", re.S)
ITALIC_RE = re.compile(r"(?<![\*\w])\*([^*\n]+)\*(?!\*)")


def inline(text: str) -> str:
    """Convert a Markdown inline span to ReportLab's mini-HTML."""
    parts = text.split("`")
    out: list[str] = []
    for i, part in enumerate(parts):
        if i % 2 == 1:  # inside backticks: literal code, no further markup
            out.append(f'<font face="{CODE_FONT}" size="8.6">{html.escape(part)}</font>')
            continue
        chunk = html.escape(part)
        chunk = LINK_RE.sub(
            lambda m: f'<link href="{m.group(2)}" color="#1F4E79"><u>{m.group(1)}</u></link>',
            chunk)
        chunk = BOLD_RE.sub(lambda m: f"<b>{m.group(1)}</b>", chunk)
        chunk = ITALIC_RE.sub(lambda m: f"<i>{m.group(1)}</i>", chunk)
        out.append(chunk)
    return "".join(out)


def wrap_code(line: str, max_width: float) -> list[str]:
    """Hard-wrap an over-long code line at a sensible break point."""
    if pdfmetrics.stringWidth(line, CODE_FONT, CODE_SIZE) <= max_width:
        return [line]
    char_w = pdfmetrics.stringWidth("M", CODE_FONT, CODE_SIZE)
    limit = max(24, int(max_width / char_w))
    indent = len(line) - len(line.lstrip(" "))
    pad = " " * min(indent + 4, 20)
    pieces: list[str] = []
    rest = line
    while pdfmetrics.stringWidth(rest, CODE_FONT, CODE_SIZE) > max_width:
        window = rest[:limit]
        cut = max(window.rfind(" "), window.rfind(","), window.rfind("("),
                  window.rfind("."), window.rfind("="))
        if cut < limit // 3:
            cut = limit
        pieces.append(rest[:cut])
        rest = pad + rest[cut:].lstrip(" ")
    pieces.append(rest)
    return pieces


# --------------------------------------------------------------------------- blocks
def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:70]


def make_heading(level: int, text: str, styles, keys: dict[str, int]):
    """Heading paragraph carrying the metadata afterFlowable() needs."""
    style = {0: styles["chapter"], 1: styles["question"], 2: styles["sub"]}[min(level, 2)]
    if text.startswith("Chapter "):
        style = styles["chapter"]
    key = slugify(text)
    keys[key] = keys.get(key, 0) + 1
    if keys[key] > 1:
        key = f"{key}-{keys[key]}"
    para = Paragraph(inline(text), style)
    para.toc_level = level
    para.toc_text = re.sub(r"\s+", " ", re.sub(r"[`*]", "", text))
    para.toc_key = key
    return para


def code_flowable(lines: list[str], styles) -> Table:
    inner_w = FRAME_W - 12
    wrapped: list[str] = []
    for line in lines:
        wrapped.extend(wrap_code(line.replace("\t", "    "), inner_w - 8))
    pre = Preformatted("\n".join(wrapped) or " ", styles["code"])
    table = Table([[pre]], colWidths=[FRAME_W])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CODE_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, CODE_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def table_flowable(rows: list[list[str]], styles) -> Table:
    header, *body = rows
    ncols = max(len(r) for r in rows)
    header = header + [""] * (ncols - len(header))
    body = [r + [""] * (ncols - len(r)) for r in body]

    weights = []
    for col in range(ncols):
        longest = max([len(header[col])] + [len(r[col]) for r in body] or [1])
        weights.append(max(6, min(longest, 90)))
    total = sum(weights)
    widths = [FRAME_W * w / total for w in weights]

    data = [[Paragraph(inline(c), styles["cellhead"]) for c in header]]
    data += [[Paragraph(inline(c), styles["cell"]) for c in r] for r in body]

    table = Table(data, colWidths=widths, repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F5F8")]),
        ("GRID", (0, 0), (-1, -1), 0.4, RULE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table


def parse(markdown: str, styles) -> list:
    """Translate the manuscript into a flowable story."""
    story: list = []
    keys: dict[str, int] = {}
    lines = markdown.splitlines()
    i = 0
    skip_section = False          # used to drop the Markdown-only "Contents" block
    first_chapter_seen = False
    para_buf: list[str] = []
    bullet_buf: list[str] = []

    def flush_para():
        """Join buffered lines, honouring Markdown hard breaks (two trailing spaces)."""
        nonlocal para_buf
        if para_buf:
            text = ""
            for n, raw in enumerate(para_buf):
                if n:
                    text += "<br/>" if para_buf[n - 1].endswith("  ") else " "
                text += inline(raw.strip())
            story.append(Paragraph(text.strip(), styles["body"]))
            para_buf = []

    def flush_bullets():
        nonlocal bullet_buf
        if bullet_buf:
            items = [ListItem(Paragraph(inline(b), styles["bullet"]), leftIndent=13,
                              value="bulletchar") for b in bullet_buf]
            story.append(ListFlowable(items, bulletType="bullet", bulletFontSize=6,
                                      bulletOffsetY=-1.2, leftIndent=13, start="circle",
                                      spaceBefore=1, spaceAfter=6))
            bullet_buf = []

    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            flush_para(); flush_bullets()
            i += 1
            block: list[str] = []
            while i < len(lines) and not lines[i].startswith("```"):
                block.append(lines[i]); i += 1
            i += 1
            if not skip_section:
                story.append(Spacer(1, 3))
                story.append(code_flowable(block, styles))
                story.append(Spacer(1, 7))
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", line)
        if heading:
            flush_para(); flush_bullets()
            depth, text = len(heading.group(1)), heading.group(2).strip()
            if text == TITLE:                      # the title page covers this
                skip_section = True; i += 1; continue
            if text == "Contents":                 # generated TOC replaces it
                skip_section = True; i += 1; continue
            skip_section = False
            is_chapter = text.startswith("Chapter ")
            is_question = bool(re.match(r"^Q\d{3}\.", text))
            if is_chapter or (depth <= 2 and not is_question):
                if story and not isinstance(story[-1], PageBreak):
                    story.append(PageBreak())
                first_chapter_seen = True
                para = make_heading(0, text, styles, keys)
                if not is_chapter:
                    para.style = styles["section"]
                story.append(para)
            elif is_question:
                story.append(make_heading(1, text, styles, keys))
            else:
                story.append(make_heading(2, text, styles, keys))
            i += 1
            continue

        if skip_section:
            i += 1
            continue

        if line.strip() in {"---", "***", "___"}:
            flush_para(); flush_bullets()
            i += 1
            continue

        if line.startswith("|") and i + 1 < len(lines) and re.match(
                r"^\|[\s:|-]+\|?$", lines[i + 1].strip()):
            flush_para(); flush_bullets()
            rows = [split_row(line)]
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                rows.append(split_row(lines[i])); i += 1
            story.append(Spacer(1, 3))
            story.append(table_flowable(rows, styles))
            story.append(Spacer(1, 8))
            continue

        bullet = re.match(r"^\s*[-*]\s+(.*)$", line)
        if bullet:
            flush_para()
            bullet_buf.append(bullet.group(1).strip())
            i += 1
            continue

        numbered = re.match(r"^\s*(\d+)\.\s+(.*)$", line)
        if numbered:
            flush_para(); flush_bullets()
            story.append(Paragraph(
                f"<b>{numbered.group(1)}.</b> {inline(numbered.group(2).strip())}",
                ParagraphStyle("num", parent=styles["body"], leftIndent=13,
                               firstLineIndent=-13, spaceAfter=3)))
            i += 1
            continue

        if not line.strip():
            flush_para(); flush_bullets()
            i += 1
            continue

        para_buf.append(line.strip() + "  " if line.endswith("  ") else line.strip())
        i += 1

    flush_para(); flush_bullets()
    del first_chapter_seen
    return story


# --------------------------------------------------------------------------- document
class BookDoc(BaseDocTemplate):
    def __init__(self, path: str, total_holder: dict, **kw):
        super().__init__(path, **kw)
        self.total_holder = total_holder
        frame = Frame(MARGIN_X, MARGIN_BOTTOM, FRAME_W,
                      PAGE_H - MARGIN_TOP - MARGIN_BOTTOM, id="body",
                      leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)
        self.addPageTemplates([
            PageTemplate(id="plain", frames=[frame], onPage=self.decorate_plain),
            PageTemplate(id="cover", frames=[frame]),
        ])

    def decorate_plain(self, canvas, doc):
        if doc.page <= 1:
            return
        canvas.saveState()
        canvas.setStrokeColor(RULE)
        canvas.setLineWidth(0.4)
        y = PAGE_H - MARGIN_TOP + 6
        canvas.line(MARGIN_X, y, PAGE_W - MARGIN_X, y)
        canvas.setFont("Helvetica", 7.4)
        canvas.setFillColor(colors.HexColor("#6B7B8C"))
        canvas.drawString(MARGIN_X, y + 4, "Top 200 Java Backend Developer Interview Questions")
        canvas.drawRightString(PAGE_W - MARGIN_X, y + 4, "3-4 years experience")
        canvas.line(MARGIN_X, MARGIN_BOTTOM - 8, PAGE_W - MARGIN_X, MARGIN_BOTTOM - 8)
        total = self.total_holder.get("total")
        label = f"Page {doc.page} of {total}" if total else f"Page {doc.page}"
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(PAGE_W - MARGIN_X, MARGIN_BOTTOM - 18, label)
        canvas.restoreState()

    def afterFlowable(self, flowable):
        level = getattr(flowable, "toc_level", None)
        if level is None:
            return
        key = flowable.toc_key
        self.canv.bookmarkPage(key)
        # PDF outlines may not skip a level, so clamp to one deeper than the last entry.
        last = getattr(self, "_last_outline_level", -1)
        outline_level = min(level, last + 1, 2)
        self._last_outline_level = outline_level
        self.canv.addOutlineEntry(flowable.toc_text[:120], key.encode("utf-8"),
                                  level=outline_level, closed=(outline_level == 0))
        if level <= 1:
            self.notify("TOCEntry", (level, flowable.toc_text, self.page, key))


def cover(styles) -> list:
    built = date.today().isoformat()
    return [
        Spacer(1, 52 * mm),
        Paragraph(TITLE, styles["title"]),
        Paragraph(SUBTITLE, styles["subtitle"]),
        Paragraph(
            "Java 17 and 21 &bull; Spring Boot 3 &bull; REST and HTTP &bull; PostgreSQL "
            "&bull; JPA and Hibernate<br/>JUnit 5 and Mockito &bull; Maven and Gradle "
            "&bull; Redis &bull; Kafka &bull; Docker &bull; Observability",
            styles["titlemeta"]),
        Spacer(1, 16 * mm),
        Paragraph(
            "200 questions numbered Q001 to Q200, each with a priority, a spoken answer "
            "of roughly 45 to 90 seconds, an in-depth explanation, a practical backend "
            "example, common follow-ups, mistakes to avoid and a production perspective.",
            styles["titlemeta"]),
        Spacer(1, 10 * mm),
        Paragraph(f"Generated from the Markdown sources on {built}", styles["titlemeta"]),
        PageBreak(),
    ]


def build(total_holder: dict, styles) -> int:
    markdown = SOURCE.read_text(encoding="utf-8")
    toc = TableOfContents()
    toc.levelStyles = toc_styles()
    toc.dotsMinLevel = 0

    story: list = []
    story += cover(styles)
    story.append(Paragraph("Contents", styles["toctitle"]))
    story.append(toc)
    story += parse(markdown, styles)

    doc = BookDoc(str(OUTPUT), total_holder, pagesize=A4,
                  title=TITLE, author="Java Backend Interview Guide",
                  subject="Java backend developer interview preparation",
                  creator="build_pdf.py (ReportLab)")
    doc.multiBuild(story)
    return doc.page


def main() -> int:
    if not SOURCE.exists():
        sys.exit(f"missing {SOURCE}; run scripts/build_book.py first")
    styles = build_styles()
    holder: dict[str, int] = {}
    pages = build(holder, styles)          # pass 1: discover the page count
    holder["total"] = pages
    pages = build(holder, styles)          # pass 2: footers with "Page N of M"
    size = OUTPUT.stat().st_size
    print(f"wrote {OUTPUT.relative_to(ROOT.parent)}")
    print(f"  pages={pages} bytes={size}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
